// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                pgtype.UUID      `json:"id"`
	Name              string           `json:"name"`
	PhoneNumber       string           `json:"phone_number"`
	Opt               string           `json:"opt"`
	OptExpirationTime pgtype.Timestamp `json:"opt_expiration_time"`
}
